// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzdyhpdrcohsdvojjckf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZHlocGRyY29oc2R2b2pqY2tmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDkxODMsImV4cCI6MjA2NjcyNTE4M30.6AtFd4yTaBoSgIBbliqvR0oey4zFTktdBGiuYHAw5_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);